export type { MasterSheet, IndentSheet, ReceivedSheet, Sheet, allPermissionKeys, Vendor, UserPermissions, InventorySheet, IssueSheet, StoreInSheet , TallyEntrySheet , PcReportSheet , FullkittingSheet ,PaymentHistory} from "./sheets";
export { type ProductFormValues,type ProductItemProps, type Options,type  FormValues, formSchema } from "./indentForm";
export { type RouteAttributes } from "./routes";
export type PoMasterSheet = {
    timestamp: string;
    partyName: string;
    poNumber: string;
    quotationNumber: string;
    quotationDate: string;
    enquiryNumber: string;
    enquiryDate: string;
    internalCode: string;
    product: string;
    description: string;
    quantity: number;
    unit: string;
    rate: number;
    gstPercent: number;
    discountPercent: number;
    amount: number;
    totalPoAmount: number;
    deliveryDate: string;
    paymentTerms: string;
    numberOfDays: number;
    deliveryDays: number;
    deliveryType: string;
    term1: string;
    term2: string;
    term3: string;
    term4: string;
    term5: string;
    term6: string;
    term7: string;
    term8: string;
    term9: string;
    term10: string;
    pdf?: string;
    preparedBy?: string;
    approvedBy?: string;
    emailSendStatus?: string;
    firmNameMatch?: string;
}